kind: PersistentVolume
apiVersion: v1
metadata:
  name: mysql-data
  labels:
    type: local
spec:
  storageClassName: mysql-data
  capacity:
    storage: 100M
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/zipkin"

